---

- name: include variables from sulfur config
  include_vars: /etc/sulfur/sulfur.yml

- name: install packages
  yum: pkg={{ item }} state=present
  with_items:
    - bind
    - bind-utils
    - bitrix-env



